version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: quickerp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quickerp
      MYSQL_USER: quickerp_user
      MYSQL_PASSWORD: quickerp_user123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
